name: Deploy Documentation

on:
  push:
    branches:
      - main

# ADICIONE ESTE BLOCO AQUI:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build and Deploy
        run: uv run mkdocs gh-deploy --force